name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image with dev dependencies
        run: docker build --build-arg DEV=true -t myapp .

      - name: Run tests
        run: docker-compose run --rm app sh -c "python manage.py test"

      - name: Run linter
        run: docker-compose run --rm app sh -c "flake8"
